;;; dape-deep-project.el --- Project setup and diagnostics -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Di Xiu

;; Author: Di Xiu <dyi.shiou@gmail.com>
;; Assisted-by: Claude Code:claude-fable-5
;; Assisted-by: Claude Code:deepseek-v4.1-flash
;; Assisted-by: Codex:gpt-5.6-sol
;; URL: https://github.com/lemyx/dape-deep
;; License: GPL-3.0-or-later

;; This file is part of dape-deep.

;; This package is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This package is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:
;;
;; Plan, preview, and atomically apply the small project files needed for a
;; split local/remote Python workflow.  Owned regions can be updated safely;
;; files already owned by the user are reported as manual actions.

;;; Code:

(require 'dape-deep-bootstrap)
(require 'dape-deep-config)
(require 'project)
(require 'subr-x)

(defconst dape-deep--dir-locals-header
  ";;; Generated by dape-deep; edit package variables instead.\n")

(defconst dape-deep--project-marker-content
  "This file marks the project root for Emacs project.el.\n")

(defun dape-deep--current-python-script ()
  "Return the current file buffer's Python basename.
Signal a user error unless the current buffer visits a .py file."
  (unless buffer-file-name
    (user-error "Run project setup from a buffer visiting a Python file"))
  (let ((name (file-name-nondirectory buffer-file-name)))
    (unless (string-match-p "\\.py\\'" name)
      (user-error "Project setup target must be a .py file: %s" name))
    name))

(defun dape-deep--script-below-root (script root)
  "Return SCRIPT's path relative to ROOT for the current file buffer.
SCRIPT is used unchanged when the buffer's file is not below ROOT.  Relative
paths let the generated launcher start an entry file in a subdirectory, since
it runs from the project root."
  (if (file-in-directory-p buffer-file-name root)
      (file-relative-name buffer-file-name root)
    script))

(defun dape-deep--register-project-marker ()
  "Teach project.el that .project can mark a VC project root."
  (when (boundp 'project-vc-extra-root-markers)
    (add-to-list 'project-vc-extra-root-markers ".project")))

(dape-deep--register-project-marker)

(defun dape-deep--project-root (&optional directory)
  "Return the dape-deep project root containing DIRECTORY.
Search upward from DIRECTORY, or `default-directory', for the nearest
`.project' marker.  This gives a configured subtree precedence over an
enclosing VCS project, even when project.el has cached the outer project.
Fall back to the current project root, then to DIRECTORY itself."
  (let* ((directory (or directory default-directory))
         (marker-directory (locate-dominating-file directory ".project")))
    (file-name-as-directory
     (expand-file-name
      (or marker-directory
          (when-let* ((project (project-current nil directory)))
            (project-root project))
          directory)))))

(defun dape-deep--default-remote-root (local-root &optional remote-home)
  "Return a topology-preserving remote root for LOCAL-ROOT.
Place the result below REMOTE-HOME, defaulting to /root.  Mirror LOCAL-ROOT
below the nearest anchor it has, so that the local depth is preserved: the Git
repository containing it, whose own name becomes the top-level directory of the
mirror, or else the local home directory.  A LOCAL-ROOT below neither anchor is
placed below REMOTE-HOME by basename alone."
  (let* ((local-root (file-name-as-directory (expand-file-name local-root)))
         (git-root (locate-dominating-file local-root ".git"))
         (home (file-name-as-directory (expand-file-name "~")))
         (name (file-name-nondirectory (directory-file-name local-root)))
         (remote-home (file-name-as-directory (or remote-home "/root"))))
    (cond
     ;; A repository is mirrored under its own name, and a project below the
     ;; local home under the path it has there; both keep the local depth.
     (git-root
      (directory-file-name
       (expand-file-name (file-relative-name local-root git-root)
                         (expand-file-name
                          (file-name-nondirectory
                           (directory-file-name git-root))
                          remote-home))))
     ;; A LOCAL-ROOT that is the local home itself keeps its basename instead:
     ;; mirroring it would map the whole home onto REMOTE-HOME.
     ((and (not (equal local-root home))
           (file-in-directory-p local-root home))
      (directory-file-name
       (expand-file-name (file-relative-name local-root home) remote-home)))
     (t (unless (string-empty-p name)
          (directory-file-name (expand-file-name name remote-home)))))))

(defconst dape-deep--remote-python-probe-code
  (concat
   "import sys; "
   "print('DAPE_DEEP_PYTHON=' + sys.executable); "
   "print('DAPE_DEEP_VERSION=%d.%d' % sys.version_info[:2])")
  "Python code used to report a remote interpreter and its major/minor version.")

(defun dape-deep--remote-python-probe-command (host)
  "Return the SSH argv used to detect Python on HOST.
Use the configured target shell, but disable pseudo-terminal allocation so the
machine-readable output is not polluted by terminal control characters."
  (let* ((timeout (max 1 dape-deep-ssh-probe-timeout))
         (probe-body
          (format
           (concat "printf 'DAPE_DEEP_HOME=%%s\\n' \"$HOME\"; "
                   "python=$(command -v python3 2>/dev/null || "
                   "command -v python 2>/dev/null) || exit 127; "
                   "\"$python\" -c %s")
           (shell-quote-argument dape-deep--remote-python-probe-code)))
         (wrapped-command
          (concat
           (mapconcat #'shell-quote-argument dape-deep-shell-command " ")
           " " (shell-quote-argument probe-body)))
         (ssh-arguments
          (seq-remove (lambda (argument)
                        (member argument '("-t" "-tt")))
                      dape-deep-ssh-arguments)))
    (append (list dape-deep-ssh-program
                  "-T"
                  "-o" "BatchMode=yes"
                  "-o" (format "ConnectTimeout=%d" timeout))
            ssh-arguments
            (list "--" host wrapped-command))))

(defun dape-deep--parse-remote-python-probe (output)
  "Return remote HOME and Python information parsed from OUTPUT, or nil."
  (let (home executable version result)
    (when (string-match
           "^DAPE_DEEP_HOME=\\(.+\\)\r?$" output)
      (setq home (match-string 1 output)))
    (when (string-match
           "^DAPE_DEEP_PYTHON=\\(.+\\)\r?$" output)
      (setq executable (match-string 1 output)))
    (when (string-match
           "^DAPE_DEEP_VERSION=\\([0-9]+\\.[0-9]+\\)\r?$" output)
      (setq version (match-string 1 output)))
    (when (and home (file-name-absolute-p home))
      (setq result (list :home home)))
    (when (and executable version (file-name-absolute-p executable))
      (setq result (plist-put result :executable executable)
            result (plist-put result :version version)))
    result))

(defun dape-deep--probe-remote-python (host)
  "Best-effort detection of the Python executable and version on HOST.
Return a plist containing :executable and :version, or nil.  Connect without
interactive authentication and give up after `dape-deep-ssh-probe-timeout'
seconds so project setup always remains usable through manual input."
  (when (and (stringp host)
             (not (string-empty-p host))
             (not (string-prefix-p "-" host))
             (not (string-match-p "[[:space:]]" host)))
    (let ((buffer (generate-new-buffer " *dape-deep python probe*"))
          (deadline (+ (float-time) (max 1 dape-deep-ssh-probe-timeout)))
          process
          result)
      (unwind-protect
          (condition-case nil
              (progn
                (message "dape-deep: detecting Python on %s ..." host)
                (setq process
                      (make-process
                       :name "dape-deep python probe"
                       :buffer buffer
                       :stderr buffer
                       :command (dape-deep--remote-python-probe-command host)
                       :connection-type 'pipe
                       :coding 'utf-8-unix
                       :noquery t))
                (while (and (process-live-p process)
                            (< (float-time) deadline))
                  (accept-process-output process 0.05))
                (setq result
                      (dape-deep--parse-remote-python-probe
                       (with-current-buffer buffer (buffer-string))))
                (if (process-live-p process)
                    (message "dape-deep: Python detection timed out on %s"
                             host)
                  (accept-process-output process 0.01)
                  (setq result
                        (dape-deep--parse-remote-python-probe
                         (with-current-buffer buffer (buffer-string))))
                  (cond
                   ((plist-get result :executable)
                      (message "dape-deep: detected %s (Python %s)"
                               (plist-get result :executable)
                               (plist-get result :version)))
                   (result
                    (message (concat "dape-deep: detected remote home on %s, "
                                     "but not Python")
                             host))
                   (t
                    (message "dape-deep: could not detect Python on %s"
                             host)))))
            (error
             (message "dape-deep: could not run Python detection on %s"
                      host)))
        (when (process-live-p process)
          (delete-process process))
        (kill-buffer buffer))
      result)))

(defun dape-deep--read-file (path)
  "Return PATH contents without text properties, or nil if it is absent."
  (when (file-exists-p path)
    (with-temp-buffer
      (insert-file-contents path)
      (buffer-string))))

(defun dape-deep--atomic-write (path content &optional mode)
  "Atomically replace PATH with CONTENT and preserve its MODE when possible.
A symbolic link is written through rather than replaced: ~/.ssh/config and
project files are often links into a dotfiles repository, and turning one into
a regular file would quietly detach it from the file the user maintains."
  (let* ((path (file-truename path))
         (directory (file-name-directory path))
         (old-mode (and (file-exists-p path) (file-modes path)))
         (temp nil))
    (make-directory directory t)
    (setq temp (make-temp-file
                (expand-file-name ".dape-deep-write-" directory)))
    (unwind-protect
        (progn
          (write-region content nil temp nil 'silent)
          (set-file-modes temp (or mode old-mode #o644))
          (rename-file temp path t)
          (setq temp nil))
      (when (and temp (file-exists-p temp))
        (delete-file temp)))))

(defun dape-deep--toml-string (value)
  "Encode VALUE as a basic TOML string."
  (unless (and (stringp value) (not (string-match-p "[\n\r]" value)))
    (user-error "TOML value must be a single-line string: %S" value))
  (concat "\""
          (replace-regexp-in-string
           "\"" "\\\\\""
           (replace-regexp-in-string "\\\\" "\\\\\\\\" value t t)
           t t)
          "\""))

(defun dape-deep--managed-block (name body)
  "Wrap BODY in package ownership markers named NAME."
  (format "# dape-deep: begin %s\n%s# dape-deep: end %s\n"
          name body name))

(defun dape-deep--string-count (needle haystack)
  "Return the number of non-overlapping NEEDLE occurrences in HAYSTACK."
  (let ((start 0)
        (count 0))
    (while (string-match (regexp-quote needle) haystack start)
      (setq count (1+ count)
            start (match-end 0)))
    count))

(defun dape-deep--replace-managed-block (content name block conflict-re)
  "Return the proposed CONTENT after replacing NAME with BLOCK.
Return the symbol `conflict' for incomplete markers or an unmanaged section
matching CONFLICT-RE."
  (let* ((begin (format "# dape-deep: begin %s" name))
         (end (format "# dape-deep: end %s" name))
         (begin-count (dape-deep--string-count begin content))
         (end-count (dape-deep--string-count end content))
         (begin-pos (string-match (concat "^" (regexp-quote begin) "$") content))
         (end-pos (string-match (concat "^" (regexp-quote end) "$") content)))
    (cond
     ((and (= begin-count 1) (= end-count 1)
           begin-pos end-pos (< begin-pos end-pos))
      (let ((end-line (or (string-match "\n" content end-pos)
                          (length content))))
        (concat (substring content 0 begin-pos)
                block
                (substring content
                           (if (< end-line (length content)) (1+ end-line) end-line)))))
     ((or (> begin-count 0) (> end-count 0)) 'conflict)
     ((and conflict-re (string-match-p conflict-re content)) 'conflict)
     (t
      (concat content
              (unless (or (string-empty-p content) (string-suffix-p "\n" content)) "\n")
              (unless (string-empty-p content) "\n")
              block)))))

(defun dape-deep--managed-block-only-p (content name)
  "Return non-nil when CONTENT holds nothing but the managed block NAME.
Only such a file was created by the package, which may then keep it out of
version control.  A file the user has written anything of their own into is
theirs, and must keep showing up for `git status'."
  (let* ((begin (format "# dape-deep: begin %s" name))
         (end (format "# dape-deep: end %s" name))
         (begin-pos (and (stringp content)
                         (string-match (concat "^" (regexp-quote begin) "$")
                                       content)))
         (end-pos (and begin-pos
                       (string-match (concat "^" (regexp-quote end) "$")
                                     content (match-end 0)))))
    (and end-pos
         (string-blank-p (substring content 0 begin-pos))
         (string-blank-p (substring content (match-end 0))))))

(defun dape-deep--plan-item (path before after description
                                            &optional status)
  "Construct a plan item for PATH from BEFORE to AFTER with DESCRIPTION.
Use STATUS instead of inferring create, update, or unchanged when non-nil."
  (list :path path
        :exists (not (null before))
        :before before
        :after after
        :description description
        :status (or status
                    (cond
                     ((null before) 'create)
                     ((string-equal before after) 'unchanged)
                     (t 'update)))))

(defconst dape-deep--gitignore-begin
  "# dape-deep: begin project artifacts")

(defconst dape-deep--gitignore-end
  "# dape-deep: end project artifacts")

(defun dape-deep--gitignore-patterns (&optional ty-ignored)
  "Return the package artifacts that must stay out of version control.
Patterns are anchored at the project root, so a same-named file elsewhere in
the repository keeps its own lifecycle.  TY-IGNORED adds the ty.toml the
package creates; a ty.toml the user has added settings of their own to is
theirs, and stays visible to version control."
  (append (list "/.project" "/.dir-locals.el")
          (when ty-ignored
            (list "/ty.toml"))
          (list (concat "/" dape-deep-target-script))))

(defun dape-deep--gitignore-block (&optional ty-ignored)
  "Return the managed .gitignore block for this package's artifacts.
TY-IGNORED is passed on to `dape-deep--gitignore-patterns'."
  (concat dape-deep--gitignore-begin "\n"
          (mapconcat #'identity (dape-deep--gitignore-patterns ty-ignored) "\n")
          "\n" dape-deep--gitignore-end "\n"))

(defun dape-deep--gitignore-content (before &optional ty-ignored)
  "Return .gitignore contents that keep this package's artifacts untracked.
BEFORE is the current contents, or nil when the file does not exist.  Entries
in a user-owned file are preserved, because ignore patterns are additive; an
existing managed block is updated in place.  TY-IGNORED is passed on to
`dape-deep--gitignore-block'."
  (if before
      (dape-deep--replace-managed-block
       before "project artifacts" (dape-deep--gitignore-block ty-ignored) nil)
    (dape-deep--gitignore-block ty-ignored)))

(defconst dape-deep--conflict-start
  "<<<<<<< existing (yours)")

(defconst dape-deep--conflict-separator
  "=======")

(defconst dape-deep--conflict-end
  ">>>>>>> dape-deep (generated)")

(defun dape-deep--line-end (text)
  "Return TEXT with a trailing newline unless it is empty or already has one."
  (if (or (string-empty-p text) (string-suffix-p "\n" text))
      text
    (concat text "\n")))

(defun dape-deep--conflict-content (theirs ours)
  "Return THEIRS and OURS separated by git-style conflict markers."
  (concat dape-deep--conflict-start "\n"
          (dape-deep--line-end theirs)
          dape-deep--conflict-separator "\n"
          (dape-deep--line-end ours)
          dape-deep--conflict-end))

(defun dape-deep--unresolved-conflict-p (content)
  "Return non-nil when CONTENT still holds conflict markers."
  (and (stringp content)
       (string-match-p "^<<<<<<<" content)))

(defun dape-deep--toml-section-bounds (content header-re)
  "Return the bounds of the section of CONTENT that starts at HEADER-RE, or nil.
The bounds end after the newline that terminates the section text, so a
replacement of the same shape leaves the blank lines before the next table
header exactly as they were."
  (when (string-match header-re content)
    (let* ((start (match-beginning 0))
           (limit (if (string-match "^[[:space:]]*\\[" content (match-end 0))
                      (match-beginning 0)
                    (length content)))
           (text (string-trim-right (substring content start limit)))
           (text-end (+ start (length text))))
      (cons start (if (eq (aref content text-end) ?\n)
                      (1+ text-end)
                    text-end)))))

(defun dape-deep--toml-section (content header-re)
  "Return the section of CONTENT that starts at HEADER-RE, or nil.
A section ends where the next table header begins."
  (when-let* ((bounds (dape-deep--toml-section-bounds content header-re)))
    (substring content (car bounds) (cdr bounds))))

(defun dape-deep--replace-toml-section (content header-re replacement)
  "Return CONTENT with the section at HEADER-RE replaced by REPLACEMENT.
Return CONTENT unchanged when it holds no such section."
  (if-let* ((bounds (dape-deep--toml-section-bounds content header-re)))
      (concat (substring content 0 (car bounds))
              (dape-deep--line-end replacement)
              (substring content (cdr bounds)))
    content))

(defconst dape-deep--ty-environment-re
  "^[[:space:]]*\\[environment\\][[:space:]]*$")

(defun dape-deep--conflict-ty-environment (content ours)
  "Return CONTENT with its `[environment]' section marked as a conflict.
OURS is the managed section to offer against it.  Only that section is
replaced, so every other table, key, and comment in the file survives; a file
without the section gains the marked block at its end."
  (let* ((marked (dape-deep--conflict-content
                  (or (dape-deep--toml-section
                       content dape-deep--ty-environment-re)
                      "")
                  ours))
         (replaced (dape-deep--replace-toml-section
                    content dape-deep--ty-environment-re marked)))
    (if (equal replaced content)
        (concat (dape-deep--line-end content) "\n" marked "\n")
      replaced)))

(defun dape-deep--merge-dir-locals (before ours)
  "Merge the package settings in OURS into the user-owned BEFORE.
Return a cons of a scheme and the text to write:

  (merge . TEXT)     BEFORE gained the settings it was missing
  (conflict . TEXT)  TEXT shows both values, separated by conflict markers
  (manual . nil)     BEFORE must be merged by hand and is never written

BEFORE is returned unchanged when it already holds every setting.  A file
whose text carries comments, or that does not parse, is left for a manual
merge because merging rewrites the whole form."
  (let* ((theirs (and (not (string-match-p ";" before))
                      (condition-case nil
                          (car (read-from-string before))
                        (error nil))))
         (our-form (car (read-from-string ours))))
    (if (null theirs)
        (cons 'manual nil)
      (let* ((our-entries (cdr (assq nil our-form)))
             (their-entries (cdr (assq nil theirs)))
             (other (seq-remove (lambda (entry) (eq (car entry) nil)) theirs))
             additions conflicts)
        (dolist (entry our-entries)
          (let ((present (assq (car entry) their-entries)))
            (cond ((null present) (push entry additions))
                  ((equal (cdr present) (cdr entry)))
                  (t (push entry conflicts)))))
        (if (and (null additions) (null conflicts))
            (cons 'merge before)
          (let* ((indent (lambda (text) (concat "  " text)))
                 (render (lambda (entry)
                           (funcall indent (prin1-to-string entry))))
                 (kept (mapconcat render
                                  (seq-remove
                                   (lambda (entry)
                                     (assq (car entry) conflicts))
                                   their-entries)
                                  "\n"))
                 (added (mapconcat render (nreverse additions) "\n"))
                 ;; `reverse' rather than `nreverse': the list is rendered
                 ;; twice, and `conflicts' is still read below.
                 (conflicting (reverse conflicts))
                 (marked
                  (when conflicting
                    (dape-deep--conflict-content
                     (mapconcat
                      (lambda (entry)
                        (funcall indent
                                 (prin1-to-string
                                  (assq (car entry) their-entries))))
                      conflicting "\n")
                     (mapconcat render conflicting "\n"))))
                 (lines (seq-remove #'string-empty-p
                                    (list kept added marked))))
            (cons (if conflicts 'conflict 'merge)
                  (concat "((nil"
                          (if lines (concat "\n" (string-join lines "\n")) "")
                          ;; A conflict needs the group closed on a line of its
                          ;; own: deleting the marker lines, by hand or with
                          ;; smerge-mode, would otherwise take the closing
                          ;; parentheses with them and leave unreadable elisp
                          ;; that silently disables every directory-local
                          ;; variable of the project.
                          (if conflicts "\n)" ")")
                          (dape-deep--dir-locals-lines other " ")
                          ")\n"))))))))

(defun dape-deep--local-ty-body (spec)
  "Return the managed ty.toml body for SPEC."
  (concat "[environment]\n"
          "python = " (dape-deep--toml-string
                        (plist-get spec :local-python)) "\n"
          (when-let* ((version (plist-get spec :python-version)))
            (concat "python-version = "
                    (dape-deep--toml-string version) "\n"))))

(defun dape-deep--spec-backend (spec)
  "Return the concrete execution backend selected by project SPEC."
  (let ((backend (or (plist-get spec :backend) 'auto))
        (host (plist-get spec :host)))
    (unless (dape-deep--backend-p backend)
      (user-error "Invalid project backend: %S" backend))
    (if (eq backend 'auto)
        (if (and (stringp host) (not (string-empty-p host))) 'ssh 'local)
      backend)))

(defun dape-deep--dir-locals-lines (entries indent)
  "Return ENTRIES as elisp, one per line, each indented with INDENT.
The package renders these itself rather than calling `pp-to-string', which
lays the same forms out differently in different Emacs versions.  This text
lands in a file the user owns and may keep in version control, so the same
project has to produce the same file whichever Emacs wrote it."
  (mapconcat (lambda (entry) (concat "\n" indent (prin1-to-string entry)))
             entries ""))

(defun dape-deep--dir-locals-content (spec)
  "Return generated .dir-locals.el contents for SPEC."
  (let* ((backend (dape-deep--spec-backend spec))
         (settings
          `((dape-deep-backend . ,backend)
            (dape-deep-local-root . ,(plist-get spec :local-root))
            (dape-deep-local-python . ,(plist-get spec :local-python))
            (dape-deep-python-version . ,(plist-get spec :python-version))
            (dape-deep-port . ,(plist-get spec :port))
            (dape-deep-rank . ,(or (plist-get spec :rank) 0))
            (dape-command . (dape-deep-attach))))
         (settings
          (if (eq backend 'ssh)
              (append
               `((dape-deep-host . ,(plist-get spec :host))
                 (dape-deep-remote-root . ,(plist-get spec :remote-root))
                 (dape-deep-remote-python . ,(plist-get spec :remote-python)))
               settings)
            settings)))
    (concat dape-deep--dir-locals-header
            "((nil"
            (dape-deep--dir-locals-lines settings "  ")
            "))\n")))

(defun dape-deep--target-script-content (spec)
  "Return the generated target launcher contents for SPEC."
  (format (concat "#!/usr/bin/env bash\n"
                  "set -euo pipefail\n\n"
                  "PYTHONUNBUFFERED=1 %s %s\n")
          (shell-quote-argument
           (if (eq (dape-deep--spec-backend spec) 'ssh)
               (plist-get spec :remote-python)
             (plist-get spec :local-python)))
          (shell-quote-argument (plist-get spec :python-script))))

(defun dape-deep--owned-dir-locals-p (content)
  "Return non-nil when CONTENT is a generated directory-locals file."
  (and content (string-prefix-p dape-deep--dir-locals-header content)))

(defun dape-deep--validate-project-spec (spec)
  "Validate project setup SPEC and return it."
  (dolist (key '(:root :local-root :local-python :python-script :port))
    (when (null (plist-get spec key))
      (user-error "SPEC has no %s" key)))
  (let ((backend (dape-deep--spec-backend spec))
        (root (expand-file-name (plist-get spec :root)))
        (local-root (expand-file-name (plist-get spec :local-root)))
        (host (plist-get spec :host))
        (remote-root (plist-get spec :remote-root))
        (local-python (plist-get spec :local-python))
        (remote-python (plist-get spec :remote-python))
        (python-script (plist-get spec :python-script)))
    (unless (file-directory-p root)
      (user-error "Project root does not exist: %s" root))
    (unless (file-directory-p local-root)
      (user-error "Local root does not exist: %s" local-root))
    (unless (file-in-directory-p root local-root)
      (user-error "Project root must be inside the local mapping root: %s"
                  local-root))
    (unless (dape-deep--literal-absolute-path-p local-python)
      (user-error
       "Local Python path must be absolute and without \"~\": %S" local-python))
    (when (eq backend 'ssh)
      (unless (and (stringp host) (not (string-empty-p host))
                   (not (string-prefix-p "-" host))
                   (not (string-match-p "[[:space:]]" host)))
        (user-error "Invalid SSH destination: %S" host))
      (unless (dape-deep--literal-absolute-path-p remote-root)
        (user-error
         "Remote root must be absolute and without \"~\": %S" remote-root))
      (unless (dape-deep--literal-absolute-path-p remote-python)
        (user-error
         "Remote Python path must be absolute and without \"~\": %S"
         remote-python)))
    (unless (and (stringp python-script)
                 (not (file-name-absolute-p python-script))
                 (string-match-p "\\.py\\'" python-script)
                 (file-in-directory-p (expand-file-name python-script root) root))
      (user-error "Entry file must be a .py path below the project root: %S"
                  python-script))
    (unless (dape-deep--port-p (plist-get spec :port))
      (user-error "Invalid debugpy port: %S" (plist-get spec :port)))
    (unless (natnump (or (plist-get spec :rank) 0))
      (user-error "Invalid debug rank: %S" (plist-get spec :rank))))
  spec)

(defun dape-deep-project-plan (spec)
  "Build a non-mutating project setup plan from SPEC.
SPEC must contain :root, :local-root, :local-python, :python-script, and :port.
The SSH backend additionally requires :host, :remote-root, and :remote-python.
:python-version and :rank are optional.  An existing user-owned directory-local
file becomes a manual action, while .gitignore entries are appended to a
user-owned file because ignore patterns cannot conflict with it."
  (dape-deep--validate-project-spec spec)
  (let* ((root (file-name-as-directory
                (expand-file-name (or (plist-get spec :root)
                                      (user-error "SPEC has no :root")))))
         (spec (plist-put (copy-sequence spec) :root root))
         (backend (dape-deep--spec-backend spec))
         (project-path (expand-file-name ".project" root))
         (gitignore-path (expand-file-name ".gitignore" root))
         (ty-path (expand-file-name "ty.toml" root))
         (dir-path (expand-file-name ".dir-locals.el" root))
         (target-path (expand-file-name dape-deep-target-script root))
         (legacy-dir2-path (expand-file-name ".dir-locals-2.el" root))
         (project-before (dape-deep--read-file project-path))
         (ty-file (dape-deep--read-file ty-path))
         (ty-before (or ty-file ""))
         ;; A project whose language tooling is not ty never sees the file: the
         ;; plan offers nothing, and an existing ty.toml - from an earlier setup
         ;; or from the user - is left exactly as it is.
         (ty-managed (eq dape-deep-local-lsp 'ty))
         ;; Only a file that holds nothing but the block this package writes is
         ;; kept out of version control.
         (ty-ignored
          (and ty-managed
               (or (string-blank-p ty-before)
                   (dape-deep--managed-block-only-p ty-before "local-ty"))))
         (local-block
          (when ty-managed
            (dape-deep--managed-block
             "local-ty" (dape-deep--local-ty-body spec))))
         (ty-after
          (when ty-managed
            (dape-deep--replace-managed-block
             ty-before "local-ty" local-block
             dape-deep--ty-environment-re)))
         (gitignore-before (dape-deep--read-file gitignore-path))
         (gitignore-after
          (dape-deep--gitignore-content gitignore-before ty-ignored))
         (dir-before (dape-deep--read-file dir-path))
         (target-before (dape-deep--read-file target-path))
         (legacy-dir2-before
          (dape-deep--read-file legacy-dir2-path))
         plan)
    (push (dape-deep--plan-item
           project-path project-before
           (or project-before dape-deep--project-marker-content)
           "Mark this directory as an Emacs project root")
          plan)
    (push (if (eq gitignore-after 'conflict)
              (dape-deep--plan-item
               gitignore-path gitignore-before
               (or gitignore-before "")
               "Repair the incomplete dape-deep markers in this file by hand"
               'manual)
            (dape-deep--plan-item
             gitignore-path gitignore-before gitignore-after
             "Keep package artifacts out of version control"))
          plan)
    (when ty-managed
      (push (cond
             ((dape-deep--unresolved-conflict-p ty-before)
              (dape-deep--plan-item
               ty-path ty-file
               (concat "Resolve the conflict markers in this file, then run "
                       "M-x dape-deep-setup-project again")
               "This file still holds unresolved conflict markers" 'manual))
             ((eq ty-after 'conflict)
              (dape-deep--plan-item
               ty-path ty-file
               (dape-deep--conflict-ty-environment ty-before local-block)
               "Choose the interpreter you want; the markers show both"
               'conflict))
             (t
              (dape-deep--plan-item
               ty-path ty-file ty-after
               "Configure local Python for local ty and keep this file out of rsync")))
            plan))
    (let* ((generated (dape-deep--dir-locals-content spec))
           (result (cond
                    ((or (null dir-before)
                         (dape-deep--owned-dir-locals-p dir-before))
                     (cons 'merge generated))
                    ((dape-deep--unresolved-conflict-p dir-before)
                     (cons 'unresolved nil))
                    (t (dape-deep--merge-dir-locals dir-before generated)))))
      (push (pcase (car result)
              ('merge
               (dape-deep--plan-item
                dir-path dir-before (cdr result)
                (format "Configure %s debugging and the Dape configuration"
                        backend)))
              ('conflict
               (dape-deep--plan-item
                dir-path dir-before (cdr result)
                "Choose the values you want; the markers show both" 'conflict))
              ('unresolved
               (dape-deep--plan-item
                dir-path dir-before
                (concat "Resolve the conflict markers in this file, then run "
                        "M-x dape-deep-setup-project again")
                "This file still holds unresolved conflict markers" 'manual))
              (_
               (dape-deep--plan-item
                dir-path dir-before
                (concat
                 ";; Merge these settings into your existing file:\n"
                 (string-remove-prefix
                  dape-deep--dir-locals-header generated))
                "Merge the dape-deep settings into this user-owned file by hand"
                'manual)))
            plan))
    (push (dape-deep--plan-item
           target-path target-before (dape-deep--target-script-content spec)
           (format "Launch the Python buffer with the configured %s interpreter"
                   backend))
          plan)
    (when legacy-dir2-before
      (push (if (dape-deep--owned-dir-locals-p legacy-dir2-before)
                (dape-deep--plan-item
                 legacy-dir2-path legacy-dir2-before nil
                 "Remove the obsolete generated second dir-locals file"
                 'delete)
              (dape-deep--plan-item
               legacy-dir2-path legacy-dir2-before legacy-dir2-before
               (concat "Merge any needed values into .dir-locals.el, then "
                       "remove this obsolete user-owned file")
               'manual))
            plan))
    (nreverse plan)))

(defun dape-deep-display-project-plan (plan)
  "Display PLAN without writing any files."
  (let ((buffer (get-buffer-create "*dape-deep project plan*")))
    (with-current-buffer buffer
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert "dape-deep project setup plan\n\n")
        (dolist (item plan)
          (insert (format "%-9s %s\n  %s\n"
                          (upcase (symbol-name (plist-get item :status)))
                          (plist-get item :path)
                          (plist-get item :description)))
          (pcase (plist-get item :status)
            ('conflict
             (insert "\nProposed content with conflict markers \
(resolve them, save, then run setup again):\n"
                     (plist-get item :after) "\n"))
            ('manual
             (insert "\nSuggested managed content:\n"
                     (plist-get item :after) "\n"))
            ((or 'create 'update)
             (insert "\nProposed resulting content:\n"
                     (plist-get item :after) "\n"))))
        (goto-char (point-min))
        (special-mode)))
    (display-buffer buffer)
    buffer))

(defun dape-deep-apply-project-plan (plan)
  "Apply the safe changes in PLAN and return the changed paths.
Abort before writing anything when a file changed after the plan was built.
Conflict items are written with the markers the plan prepared, so only the
files reported as `manual' are left for the user to merge by hand."
  (dolist (item plan)
    (unless (eq (plist-get item :status) 'unchanged)
      (let* ((path (plist-get item :path))
             (actual (dape-deep--read-file path))
             (expected (plist-get item :before)))
        (unless (equal actual expected)
          (user-error "File changed after preview: %s" path)))))
  (let (written)
    (dolist (item plan (nreverse written))
      (pcase (plist-get item :status)
        ((or 'create 'update 'conflict)
         (let ((path (plist-get item :path))
               (after (plist-get item :after)))
           (unless (equal after (plist-get item :before))
             (dape-deep--atomic-write path after)
             (push path written))))
        ('delete
         (delete-file (plist-get item :path))
         (push (plist-get item :path) written))))))

(defun dape-deep--revert-setup-buffer (buffer plan root no-confirm)
  "Revert setup caller BUFFER to load generated directory-local settings.
PLAN is the project setup plan and ROOT is its project root.  Do nothing for a
user-owned .dir-locals.el that requires a manual merge, or when BUFFER does not
visit a file below ROOT.  NO-CONFIRM is passed to `revert-buffer'."
  (let* ((root (file-name-as-directory (expand-file-name root)))
         (dir-locals-path (expand-file-name ".dir-locals.el" root))
         (item (seq-find
                (lambda (candidate)
                  (equal (plist-get candidate :path) dir-locals-path))
                plan)))
    (when (buffer-live-p buffer)
      (with-current-buffer buffer
        (when (and buffer-file-name
                   (file-in-directory-p (expand-file-name buffer-file-name) root)
                   item
                   (memq (plist-get item :status) '(create update unchanged))
                   (dape-deep--owned-dir-locals-p
                    (dape-deep--read-file dir-locals-path)))
          ;; Match `M-x revert-buffer': refresh the file contents and rerun
          ;; normal-mode initialization so newly-created directory locals are
          ;; applied to the buffer that invoked setup.
          (revert-buffer nil no-confirm))))))

(defun dape-deep--inject-setup-buffer (buffer)
  "Ensure BUFFER has a saved bootstrap inside its Python main guard.
Skip an existing managed bootstrap."
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (unless (dape-deep--bootstrap-bounds)
        (when (dape-deep-inject-main)
          (save-buffer))))))

(defun dape-deep--read-setup-spec ()
  "Interactively read a project setup specification."
  (let* ((script-name (dape-deep--current-python-script))
         (default-root (dape-deep--project-root))
         (root (file-name-as-directory
                (read-directory-name "Project root: " default-root nil t)))
         (python-script (dape-deep--script-below-root script-name root))
         (backend
          (intern
           (completing-read
            "Execution backend: " '("local" "ssh") nil t nil nil
            (symbol-name (dape-deep--effective-backend)))))
         (local-root
          (if (eq backend 'ssh)
              (file-name-as-directory
               (read-directory-name "Local source mapping root: " root nil t))
            root))
         (default-local-python
          (or dape-deep-local-python
              dape-deep--default-local-python))
         (local-python
          (read-file-name "Local Python interpreter: "
                          (file-name-directory default-local-python)
                          default-local-python nil
                          (file-name-nondirectory default-local-python)))
         (host
          (when (eq backend 'ssh)
            (read-string "SSH Host alias: " dape-deep-host)))
         (remote-python-info
          (when (eq backend 'ssh)
            (dape-deep--probe-remote-python host)))
         (default-remote-root
          (when (eq backend 'ssh)
            (if (and (stringp dape-deep-remote-root)
                     (not (string-empty-p dape-deep-remote-root)))
                dape-deep-remote-root
              (dape-deep--default-remote-root
               local-root (plist-get remote-python-info :home)))))
         (remote-root
          (when (eq backend 'ssh)
            (read-string "Remote source mapping root: " default-remote-root)))
         (remote-python
          (when (eq backend 'ssh)
            (read-string
             "Remote Python interpreter: "
             (or (plist-get remote-python-info :executable)
                 dape-deep-remote-python))))
         (python-version
          (let ((value
                 (read-string
                  "Python version (optional): "
                  (or (plist-get remote-python-info :version)
                      dape-deep-python-version))))
            (unless (string-empty-p value) value))))
    (append
     (list :backend backend
           :root root
           :local-root local-root
           :local-python (expand-file-name local-python)
           :python-script python-script
           :python-version python-version
           :port (read-number "debugpy port: " dape-deep-port)
           :rank (read-number "Distributed rank to pause: "
                              dape-deep-rank))
     (when (eq backend 'ssh)
       (list :host host
             :remote-root remote-root
             :remote-python remote-python)))))

(defun dape-deep--preview-project-plan (plan)
  "Display PLAN and ask whether to apply it.
The plan buffer is removed as soon as the question is answered, and the window
layout in use before the command is restored, because the buffer and its window
are both closed inside the excursion that owns it."
  (save-window-excursion
    (let ((buffer (dape-deep-display-project-plan plan))
          answer)
      (unwind-protect
          (setq answer (yes-or-no-p "Apply these project changes? "))
        (dape-deep--close-preview buffer))
      answer)))

;;;###autoload
(defun dape-deep-setup-project (&optional spec no-confirm)
  "Set up project files described by SPEC.
Interactively, call this from a buffer visiting the Python entry file, then
prompt for SPEC.  The plan is displayed in *dape-deep project plan* and applied
after confirmation; pass NO-CONFIRM from Lisp to skip both the preview and the
question, as the automated callers and the test suite do.  Missing entries in a
user-owned .dir-locals.el are merged into it, and a setting the file already
holds with a different value is written with conflict markers.  After an owned
.dir-locals.el is applied, revert the invoking file buffer so its new
directory-local variables take effect; pass NO-CONFIRM to `revert-buffer'.
Finally, insert the managed debugpy bootstrap in that file's `__main__' guard
and save it; an existing bootstrap is left unchanged.  The plan buffer never
outlives the command: it is removed, with the previous window layout restored,
as soon as the question is answered, and the outcome is reported with a
message."
  (interactive)
  (let* ((setup-buffer (current-buffer))
         (spec (or spec (dape-deep--read-setup-spec)))
         (plan (dape-deep-project-plan spec)))
    (if (and (not no-confirm)
             (not (dape-deep--preview-project-plan plan)))
        (progn
          (message "dape-deep: project setup skipped, nothing was written")
          nil)
      (let* ((written (dape-deep-apply-project-plan plan))
             (attention (seq-filter (lambda (item)
                                      (memq (plist-get item :status)
                                            '(manual conflict)))
                                    plan)))
        (dape-deep--revert-setup-buffer
         setup-buffer plan (plist-get spec :root) no-confirm)
        (dape-deep--inject-setup-buffer setup-buffer)
        (if attention
            (message (concat "dape-deep: wrote %d file(s); %d need your attention"
                             " (%s)\nRevert the buffer if it is open, resolve the "
                             "<<<<<<< / ======= / >>>>>>> markers (smerge-mode "
                             "helps), save, then run setup again")
                     (length written)
                     (length attention)
                     (mapconcat (lambda (item)
                                  (file-name-nondirectory (plist-get item :path)))
                                attention ", "))
          (message "dape-deep changed %d project file(s)" (length written)))
        written))))

(defun dape-deep--project-checks (root &optional backend)
  "Return doctor checks for project ROOT and execution BACKEND."
  (let* ((root (file-name-as-directory (expand-file-name root)))
         (backend (or backend (dape-deep--effective-backend)))
         (project-file (expand-file-name ".project" root))
         (ty-managed (eq dape-deep-local-lsp 'ty))
         (ty (when ty-managed
               (or (dape-deep--read-file
                    (expand-file-name "ty.toml" root))
                   "")))
         ;; This package writes the expanded path, while the option and its
         ;; default may name the same interpreter with an abbreviation such as
         ;; "~", so either spelling counts as the configured interpreter.
         (ty-python-re
          (when dape-deep-local-python
            (regexp-opt (delete-dups
                         (list dape-deep-local-python
                               (expand-file-name dape-deep-local-python)))))))
    (append
     (list
      (list :name "execution backend" :ok (memq backend '(local ssh))
            :detail (symbol-name backend))
      (list :name ".project marker" :ok (file-exists-p project-file)
            :detail project-file))
     (when ty-managed
       (list
        (list :name "local ty Python" :ok
              (and ty-python-re (string-match-p ty-python-re ty))
              :detail (or dape-deep-local-python "unset"))))
     (list
      (list :name "local Python executable" :ok
            (and dape-deep-local-python
                 (file-executable-p dape-deep-local-python))
            :detail (or dape-deep-local-python "unset")))
     (when (and ty-managed (eq backend 'ssh))
       (list
        (list :name "ty.toml excluded from rsync" :ok
              (member "ty.toml" dape-deep-rsync-excludes)
              :detail "local interpreter configuration must not reach the server")))
     (list
      (list :name "directory-local configuration" :ok
            (file-exists-p (expand-file-name ".dir-locals.el" root))
            :detail (expand-file-name ".dir-locals.el" root))
      (let* ((dir-locals (expand-file-name ".dir-locals.el" root))
             (content (dape-deep--read-file dir-locals))
             (problem
              (when (and content (not (string-blank-p content)))
                (cond
                 ((dape-deep--unresolved-conflict-p content)
                  (concat "resolve the <<<<<<< markers; while they are present "
                          "Emacs applies none of the settings"))
                 ((not (condition-case nil
                            (progn (ignore (read-from-string content)) t)
                          (error nil)))
                  "the file does not parse, so Emacs applies none of the settings")))))
        (list :name "directory-local settings" :ok (null problem)
              :detail (or problem dir-locals)))
      (let ((legacy (expand-file-name ".dir-locals-2.el" root)))
        (list :name "single directory-local file"
              :ok (not (file-exists-p legacy))
              :detail (if (file-exists-p legacy)
                          (format "remove obsolete %s" legacy)
                        "no obsolete .dir-locals-2.el")))
      (let ((script (expand-file-name dape-deep-target-script root)))
        (list :name "debug target script" :ok
              (and (file-regular-p script) (file-readable-p script))
              :detail script))))))

(provide 'dape-deep-project)

;;; dape-deep-project.el ends here
